import '../model/item_object.dart';

class Preferences {
  List<ItemObject> preferencesList = [
    ItemObject(id: 1, name: '3D printing'),
    ItemObject(id: 2, name: 'Acroyoga'),
    ItemObject(id: 3, name: 'Acting'),
    ItemObject(id: 4, name: 'Alternate history'),
    ItemObject(id: 5, name: 'Amateur radio'),
    ItemObject(id: 6, name: 'Animation'),
    ItemObject(id: 7, name: 'Anime'),
    ItemObject(id: 8, name: 'Art'),
    ItemObject(id: 9, name: 'Audiophilia'),
    ItemObject(id: 10, name: 'Baton twirling'),
    ItemObject(id: 11, name: 'Beatboxing'),
    ItemObject(id: 12, name: 'Beer tasting'),
    ItemObject(id: 13, name: 'Bell ringing'),
    ItemObject(id: 14, name: 'Binge watching'),
    ItemObject(id: 15, name: 'Bird watching'),
    ItemObject(id: 16, name: 'Blacksmith'),
    ItemObject(id: 17, name: 'Blogging'),
    ItemObject(id: 18, name: 'Bonsai'),
    ItemObject(id: 19, name: 'Board/tabletop games'),
    ItemObject(id: 20, name: 'Book discussion clubs'),
    ItemObject(id: 21, name: 'Book restoration'),
    ItemObject(id: 22, name: 'Bowling'),
    ItemObject(id: 23, name: 'Brazilian jiu-jitsu'),
    ItemObject(id: 24, name: 'Breadmaking'),
    ItemObject(id: 25, name: 'Bullet journaling'),
    ItemObject(id: 26, name: 'Butchering'),
    ItemObject(id: 27, name: 'Calligraphy'),
    ItemObject(id: 28, name: 'Candle making'),
    ItemObject(id: 29, name: 'Candy making'),
    ItemObject(id: 30, name: 'Car spotting'),
    ItemObject(id: 31, name: 'Car fixing & building'),
    ItemObject(id: 32, name: 'Card games'),
    ItemObject(id: 33, name: 'Cardistry'),
    ItemObject(id: 34, name: 'Ceramics'),
    ItemObject(id: 35, name: 'Chatting'),
    ItemObject(id: 36, name: 'Cheesemaking'),
    ItemObject(id: 37, name: 'Chess'),
    ItemObject(id: 38, name: 'Cleaning'),
    ItemObject(id: 39, name: 'Clothesmaking'),
    ItemObject(id: 40, name: 'Coffee roasting'),
    ItemObject(id: 41, name: 'Collecting'),
    ItemObject(id: 42, name: 'Pet care'),
    ItemObject(id: 43, name: 'Coloring'),
    ItemObject(id: 44, name: 'Communication'),
    ItemObject(id: 45, name: 'Community activism'),
    ItemObject(id: 46, name: 'Community radio'),
    ItemObject(id: 47, name: 'Computer programming'),
    ItemObject(id: 48, name: 'Confectionery'),
    ItemObject(id: 49, name: 'Conlanging'),
    ItemObject(id: 50, name: 'Construction'),
    ItemObject(id: 51, name: 'Cooking'),
    ItemObject(id: 52, name: 'Cosplaying'),
    ItemObject(id: 53, name: 'Couponing'),
    ItemObject(id: 54, name: 'Craft'),
    ItemObject(id: 55, name: 'Creative writing'),
    ItemObject(id: 56, name: 'Crocheting'),
    ItemObject(id: 57, name: 'Cross-stitch'),
    ItemObject(id: 58, name: 'Crossword puzzles'),
    ItemObject(id: 59, name: 'Cryptography'),
    ItemObject(id: 60, name: 'Cue sports'),
    ItemObject(id: 61, name: 'Dance'),
    ItemObject(id: 62, name: 'Decorating'),
    ItemObject(id: 63, name: 'Decorative birds'),
    ItemObject(id: 64, name: 'Digital arts'),
    ItemObject(id: 65, name: 'Dining'),
    ItemObject(id: 66, name: 'Diorama'),
    ItemObject(id: 67, name: 'Distro Hopping'),
    ItemObject(id: 68, name: 'Diving'),
    ItemObject(id: 69, name: 'Djembe'),
    ItemObject(id: 70, name: 'DJing'),
    ItemObject(id: 71, name: 'Do it yourself'),
    ItemObject(id: 72, name: 'Drama'),
    ItemObject(id: 73, name: 'Drawing'),
    ItemObject(id: 74, name: 'Drone racing'),
    ItemObject(id: 75, name: 'Editing'),
    ItemObject(id: 76, name: 'Electronic games'),
    ItemObject(id: 77, name: 'Electronics'),
    ItemObject(id: 78, name: 'Embroidery'),
    ItemObject(id: 79, name: 'Engraving'),
    ItemObject(id: 80, name: 'Entertaining'),
    ItemObject(id: 81, name: 'Everyday carry'),
    ItemObject(id: 82, name: 'Experimenting'),
    ItemObject(id: 83, name: 'Fantasy sports'),
    ItemObject(id: 84, name: 'Fashion'),
    ItemObject(id: 85, name: 'Fashion design'),
    ItemObject(id: 86, name: 'Feng shui decorating'),
    ItemObject(id: 87, name: 'Filmmaking'),
    ItemObject(id: 88, name: 'Fingerpainting'),
    ItemObject(id: 89, name: 'Fishfarming'),
    ItemObject(id: 90, name: 'Fishkeeping'),
    ItemObject(id: 91, name: 'Flower arranging'),
    ItemObject(id: 92, name: 'Fly tying'),
    ItemObject(id: 93, name: 'Foreign language learning'),
    ItemObject(id: 94, name: 'Furniture building'),
    ItemObject(id: 95, name: 'Gambling'),
    ItemObject(id: 96, name: 'Genealogy'),
    ItemObject(id: 97, name: 'Gingerbread house making'),
    ItemObject(id: 98, name: 'Giving advice'),
    ItemObject(id: 99, name: 'Glassblowing'),
    ItemObject(id: 100, name: 'Gardening'),
    ItemObject(id: 101, name: 'Gongfu tea'),
    ItemObject(id: 102, name: 'Graphic design'),
    ItemObject(id: 103, name: 'Gunsmithing'),
    ItemObject(id: 104, name: 'Hacking'),
    ItemObject(id: 105, name: 'Hairstyle'),
    ItemObject(id: 106, name: 'Hardware'),
    ItemObject(id: 107, name: 'Herping'),
    ItemObject(id: 108, name: 'Herp keeping'),
    ItemObject(id: 109, name: 'Hobby finding'),
    ItemObject(id: 110, name: 'Home improvement'),
    ItemObject(id: 111, name: 'Homebrewing'),
    ItemObject(id: 112, name: 'Homing pigeons'),
    ItemObject(id: 113, name: 'Houseplant care'),
    ItemObject(id: 114, name: 'Hula hooping'),
    ItemObject(id: 115, name: 'Hydroponics'),
    ItemObject(id: 116, name: 'Ice skating'),
    ItemObject(id: 117, name: 'Insect collecting'),
    ItemObject(id: 118, name: 'Inventing'),
    ItemObject(id: 119, name: 'Jewelry making'),
    ItemObject(id: 120, name: 'Jigsaw puzzles'),
    ItemObject(id: 121, name: 'Journaling'),
    ItemObject(id: 122, name: 'Judo'),
    ItemObject(id: 123, name: 'Juggling'),
    ItemObject(id: 124, name: 'Karaoke'),
    ItemObject(id: 125, name: 'Karate'),
    ItemObject(id: 126, name: 'Kendama'),
    ItemObject(id: 127, name: 'Kitemaking'),
    ItemObject(id: 128, name: 'Knife making'),
    ItemObject(id: 129, name: 'Knitting'),
    ItemObject(id: 130, name: 'Knot tying'),
    ItemObject(id: 131, name: 'Kombucha brewing'),
    ItemObject(id: 132, name: 'Kung fu'),
    ItemObject(id: 133, name: 'Kun khmer'),
    ItemObject(id: 134, name: 'Lace making'),
    ItemObject(id: 135, name: 'Lapidary'),
    ItemObject(id: 136, name: 'Leather crafting'),
    ItemObject(id: 137, name: 'Lego building'),
    ItemObject(id: 138, name: 'Livestreaming'),
    ItemObject(id: 139, name: 'Listening to music'),
    ItemObject(id: 140, name: 'Listening to podcasts'),
    ItemObject(id: 141, name: 'Lock picking'),
    ItemObject(id: 142, name: 'Machining'),
    ItemObject(id: 143, name: 'Macrame'),
    ItemObject(id: 144, name: 'Magic'),
    ItemObject(id: 145, name: 'Makeup'),
    ItemObject(id: 146, name: 'Manga'),
    ItemObject(id: 147, name: 'Massaging'),
    ItemObject(id: 148, name: 'Mazes (indoor/outdoor)'),
    ItemObject(id: 149, name: 'Mechanics'),
    ItemObject(id: 150, name: 'Meditation'),
    ItemObject(id: 151, name: 'Memory training'),
    ItemObject(id: 152, name: 'Metalworking'),
    ItemObject(id: 153, name: 'Micropatriology'),
    ItemObject(id: 154, name: 'Miniature art'),
    ItemObject(id: 155, name: 'Minimalism'),
    ItemObject(id: 156, name: 'Model building'),
    ItemObject(id: 157, name: 'Modeling'),
    ItemObject(id: 158, name: 'Model engineering'),
    ItemObject(id: 159, name: 'Music'),
    ItemObject(id: 160, name: 'Nail art'),
    ItemObject(id: 161, name: 'Needlepoint'),
    ItemObject(id: 162, name: 'Origami'),
    ItemObject(id: 163, name: 'Painting'),
    ItemObject(id: 164, name: 'Pen Spinning'),
    ItemObject(id: 165, name: 'Performance'),
    ItemObject(id: 166, name: 'Pet sitting'),
    ItemObject(id: 167, name: 'Philately'),
    ItemObject(id: 168, name: 'Photography'),
    ItemObject(id: 169, name: 'Pilates'),
    ItemObject(id: 170, name: 'Pipes'),
    ItemObject(id: 171, name: 'Planning'),
    ItemObject(id: 172, name: 'Plastic art'),
    ItemObject(id: 173, name: 'Playing musical instruments'),
    ItemObject(id: 174, name: 'Poetry'),
    ItemObject(id: 175, name: 'Poi'),
    ItemObject(id: 176, name: 'Pole dancing'),
    ItemObject(id: 177, name: 'Postcrossing'),
    ItemObject(id: 178, name: 'Pottery'),
    ItemObject(id: 179, name: 'Practical jokes'),
    ItemObject(id: 180, name: 'Pressed flower craft'),
    ItemObject(id: 181, name: 'Proofreading and editing'),
    ItemObject(id: 182, name: 'Proverbs'),
    ItemObject(id: 183, name: 'Public speaking'),
    ItemObject(id: 184, name: 'Puppetry'),
    ItemObject(id: 185, name: 'Puzzles'),
    ItemObject(id: 186, name: 'Pyrography'),
    ItemObject(id: 187, name: 'Quilling'),
    ItemObject(id: 188, name: 'Quilting'),
    ItemObject(id: 189, name: 'Quizzes'),
    ItemObject(id: 190, name: 'Radio-controlled model playing'),
    ItemObject(id: 191, name: 'Rail transport modeling'),
    ItemObject(id: 192, name: 'Rapping'),
    ItemObject(id: 193, name: 'Reading'),
    ItemObject(id: 194, name: 'Recipe creation'),
    ItemObject(id: 195, name: 'Recreational drug use'),
    ItemObject(id: 196, name: 'Refinishing'),
    ItemObject(id: 197, name: 'Reiki'),
    ItemObject(id: 198, name: 'Reviewing gadgets'),
    ItemObject(id: 199, name: 'Robot combat'),
    ItemObject(id: 200, name: 'Role-playing'),
    ItemObject(id: 201, name: 'Rubik\'s Cube'),
    ItemObject(id: 202, name: 'Scrapbooking'),
    ItemObject(id: 203, name: 'Scuba diving'),
    ItemObject(id: 204, name: 'Sculpting'),
    ItemObject(id: 205, name: 'Sewing'),
    ItemObject(id: 206, name: 'Shitposting'),
    ItemObject(id: 207, name: 'Shoemaking'),
    ItemObject(id: 208, name: 'Singing'),
    ItemObject(id: 209, name: 'Sketching'),
    ItemObject(id: 210, name: 'Skipping rope'),
    ItemObject(id: 211, name: 'Slot car'),
    ItemObject(id: 212, name: 'Shopping'),
    ItemObject(id: 213, name: 'Soapmaking'),
    ItemObject(id: 214, name: 'Social media'),
    ItemObject(id: 215, name: 'Speedrunning'),
    ItemObject(id: 216, name: 'Speculative evolution'),
    ItemObject(id: 217, name: 'Spreadsheets'),
    ItemObject(id: 218, name: 'Stamp collecting'),
    ItemObject(id: 219, name: 'Stand-up comedy'),
    ItemObject(id: 220, name: 'Storytelling'),
    ItemObject(id: 221, name: 'Stretching'),
    ItemObject(id: 222, name: 'String Figures'),
    ItemObject(id: 223, name: 'Stripping'),
    ItemObject(id: 224, name: 'Sudoku'),
    ItemObject(id: 225, name: 'Talking'),
    ItemObject(id: 226, name: 'Tabletop game'),
    ItemObject(id: 227, name: 'Taekwondo'),
    ItemObject(id: 228, name: 'Tanning (leather)'),
    ItemObject(id: 229, name: 'Tapestry'),
    ItemObject(id: 230, name: 'Tarot'),
    ItemObject(id: 231, name: 'Tattooing'),
    ItemObject(id: 232, name: 'Taxidermy'),
    ItemObject(id: 233, name: 'Telling jokes'),
    ItemObject(id: 234, name: 'Thrifting'),
    ItemObject(id: 235, name: 'Upcycling'),
    ItemObject(id: 236, name: 'Video editing'),
    ItemObject(id: 237, name: 'Video game developing'),
    ItemObject(id: 238, name: 'Video gaming'),
    ItemObject(id: 239, name: 'Video making'),
    ItemObject(id: 240, name: 'VR gaming'),
    ItemObject(id: 241, name: 'Wargaming'),
    ItemObject(id: 242, name: 'Watch making'),
    ItemObject(id: 243, name: 'Watching documentaries'),
    ItemObject(id: 244, name: 'Watching movies'),
    ItemObject(id: 245, name: 'Watching television'),
    ItemObject(id: 246, name: 'Wax sealing'),
    ItemObject(id: 247, name: 'Waxing'),
    ItemObject(id: 248, name: 'Weaving'),
    ItemObject(id: 249, name: 'Webtooning'),
    ItemObject(id: 250, name: 'Weight training'),
    ItemObject(id: 251, name: 'Welding'),
    ItemObject(id: 252, name: 'Whittling'),
    ItemObject(id: 253, name: 'Wikipedia editing'),
    ItemObject(id: 254, name: 'Wikipedia racing/Wikiracing'),
    ItemObject(id: 255, name: 'Wine tasting'),
    ItemObject(id: 256, name: 'Winemaking'),
    ItemObject(id: 257, name: 'Witchcraft'),
    ItemObject(id: 258, name: 'Wood carving'),
    ItemObject(id: 259, name: 'Woodworking'),
    ItemObject(id: 260, name: 'Word searches'),
    ItemObject(id: 261, name: 'Worldbuilding'),
    ItemObject(id: 262, name: 'Writing'),
    ItemObject(id: 263, name: 'Writing music'),
    ItemObject(id: 264, name: 'Yarn bombing'),
    ItemObject(id: 265, name: 'Yo-yoing'),
    ItemObject(id: 266, name: 'Yoga'),
    ItemObject(id: 267, name: 'Zumba'),
    ItemObject(id: 268, name: 'Outdoors and sports'),
    ItemObject(id: 269, name: 'Air sports'),
    ItemObject(id: 270, name: 'Amateur geology'),
    ItemObject(id: 271, name: 'Amusement park visiting'),
    ItemObject(id: 272, name: 'Archery'),
    ItemObject(id: 273, name: 'Auto detailing'),
    ItemObject(id: 274, name: 'Automobilism'),
    ItemObject(id: 275, name: 'Astronomy'),
    ItemObject(id: 276, name: 'Backpacking'),
    ItemObject(id: 277, name: 'Badminton'),
    ItemObject(id: 278, name: 'BASE jumping'),
    ItemObject(id: 279, name: 'Baseball'),
    ItemObject(id: 280, name: 'Basketball'),
    ItemObject(id: 281, name: 'Beachcombing'),
    ItemObject(id: 282, name: 'Beekeeping'),
    ItemObject(id: 283, name: 'Birdwatching'),
    ItemObject(id: 284, name: 'Blacksmithing'),
    ItemObject(id: 285, name: 'BMX'),
    ItemObject(id: 286, name: 'Board sports'),
    ItemObject(id: 287, name: 'Bodybuilding'),
    ItemObject(id: 288, name: 'Camping'),
    ItemObject(id: 289, name: 'Canoeing'),
    ItemObject(id: 290, name: 'Canyoning'),
    ItemObject(id: 291, name: 'Carrier pigeons'),
    ItemObject(id: 292, name: 'Car riding'),
    ItemObject(id: 293, name: 'Car tuning'),
    ItemObject(id: 294, name: 'Caving'),
    ItemObject(id: 295, name: 'City trip'),
    ItemObject(id: 296, name: 'Climbing'),
    ItemObject(id: 297, name: 'Composting'),
    ItemObject(id: 298, name: 'Croquet'),
    ItemObject(id: 299, name: 'Cycling'),
    ItemObject(id: 300, name: 'Dairy Farming'),
    ItemObject(id: 301, name: 'Dandyism'),
    ItemObject(id: 302, name: 'Darts'),
    ItemObject(id: 303, name: 'Disc golf'),
    ItemObject(id: 304, name: 'Dodgeball'),
    ItemObject(id: 305, name: 'Dog training'),
    ItemObject(id: 306, name: 'Dog walking'),
    ItemObject(id: 307, name: 'Dowsing'),
    ItemObject(id: 308, name: 'Dragon boat'),
    ItemObject(id: 309, name: 'Driving'),
    ItemObject(id: 310, name: 'Farming'),
    ItemObject(id: 311, name: 'Fishing'),
    ItemObject(id: 312, name: 'Flag football'),
    ItemObject(id: 313, name: 'Flower growing'),
    ItemObject(id: 314, name: 'Flying'),
    ItemObject(id: 315, name: 'Flying disc'),
    ItemObject(id: 316, name: 'Flying model planes'),
    ItemObject(id: 317, name: 'Foraging'),
    ItemObject(id: 318, name: 'Fossicking'),
    ItemObject(id: 319, name: 'Freestyle football'),
    ItemObject(id: 320, name: 'Fruit picking'),
    ItemObject(id: 321, name: 'Gardening'),
    ItemObject(id: 322, name: 'Geocaching'),
    ItemObject(id: 323, name: 'Ghost hunting'),
    ItemObject(id: 324, name: 'Gold prospecting'),
    ItemObject(id: 325, name: 'Graffiti'),
    ItemObject(id: 326, name: 'Groundhopping'),
    ItemObject(id: 327, name: 'Guerrilla gardening'),
    ItemObject(id: 328, name: 'Gymnastics'),
    ItemObject(id: 329, name: 'Handball'),
    ItemObject(id: 330, name: 'Herbalism'),
    ItemObject(id: 331, name: 'Herping'),
    ItemObject(id: 332, name: 'High-power rocketry'),
    ItemObject(id: 333, name: 'Hiking'),
    ItemObject(id: 334, name: 'Hobby horsing'),
    ItemObject(id: 335, name: 'Hobby tunneling'),
    ItemObject(id: 336, name: 'Hooping'),
    ItemObject(id: 337, name: 'Horseback riding'),
    ItemObject(id: 338, name: 'Hunting'),
    ItemObject(id: 339, name: 'Inline skating'),
    ItemObject(id: 340, name: 'Jogging'),
    ItemObject(id: 341, name: 'Jumping rope'),
    ItemObject(id: 342, name: 'Karting'),
    ItemObject(id: 343, name: 'Kayaking'),
    ItemObject(id: 344, name: 'Kite flying'),
    ItemObject(id: 345, name: 'Kitesurfing'),
    ItemObject(id: 346, name: 'Lacrosse'),
    ItemObject(id: 347, name: 'LARPing'),
    ItemObject(id: 348, name: 'Letterboxing'),
    ItemObject(id: 349, name: 'Lomography'),
    ItemObject(id: 350, name: 'Longboarding'),
    ItemObject(id: 351, name: 'Martial arts'),
    ItemObject(id: 352, name: 'Magnet fishing'),
    ItemObject(id: 353, name: 'Metal detecting'),
    ItemObject(id: 354, name: 'Motorcycling'),
    ItemObject(id: 355, name: 'Meteorology'),
    ItemObject(id: 356, name: 'Motor sports'),
    ItemObject(id: 357, name: 'Mountain biking'),
    ItemObject(id: 358, name: 'Mountaineering'),
    ItemObject(id: 359, name: 'Museum visiting'),
    ItemObject(id: 360, name: 'Mushroom hunting/mycology'),
    ItemObject(id: 361, name: 'Netball'),
    ItemObject(id: 362, name: 'Noodling'),
    ItemObject(id: 363, name: 'Nordic skating'),
    ItemObject(id: 364, name: 'Orienteering'),
    ItemObject(id: 365, name: 'Paintball'),
    ItemObject(id: 366, name: 'Paragliding'),
    ItemObject(id: 367, name: 'Parkour'),
    ItemObject(id: 368, name: 'Photography'),
    ItemObject(id: 369, name: 'Pickleball'),
    ItemObject(id: 370, name: 'Picnicking'),
    ItemObject(id: 371, name: 'Podcast hosting'),
    ItemObject(id: 372, name: 'Polo'),
    ItemObject(id: 373, name: 'Powerlifting'),
    ItemObject(id: 374, name: 'Public transport riding'),
    ItemObject(id: 375, name: 'Qigong'),
    ItemObject(id: 376, name: 'Radio-controlled model playing'),
    ItemObject(id: 377, name: 'Rafting'),
    ItemObject(id: 378, name: 'Railway journeys'),
    ItemObject(id: 379, name: 'Railway modelling'),
    ItemObject(id: 380, name: 'Rappelling'),
    ItemObject(id: 381, name: 'Renaissance fair'),
    ItemObject(id: 382, name: 'Renovating'),
    ItemObject(id: 383, name: 'Road biking'),
    ItemObject(id: 384, name: 'Rock climbing'),
    ItemObject(id: 385, name: 'Rock painting'),
    ItemObject(id: 386, name: 'Roller skating'),
    ItemObject(id: 387, name: 'Roundnet'),
    ItemObject(id: 388, name: 'Rugby'),
    ItemObject(id: 389, name: 'Running'),
    ItemObject(id: 390, name: 'Safari'),
    ItemObject(id: 391, name: 'Sailing'),
    ItemObject(id: 392, name: 'Sand art'),
    ItemObject(id: 393, name: 'Sandboarding'),
    ItemObject(id: 394, name: 'Scouting'),
    ItemObject(id: 395, name: 'Scuba diving'),
    ItemObject(id: 396, name: 'Sculling or rowing'),
    ItemObject(id: 397, name: 'Shooting'),
    ItemObject(id: 398, name: 'Shopping'),
    ItemObject(id: 399, name: 'Shuffleboard'),
    ItemObject(id: 400, name: 'Skateboarding'),
    ItemObject(id: 401, name: 'Skiing'),
    ItemObject(id: 402, name: 'Skimboarding'),
    ItemObject(id: 403, name: 'Skydiving'),
    ItemObject(id: 404, name: 'Slacklining'),
    ItemObject(id: 405, name: 'Sledding'),
    ItemObject(id: 406, name: 'Snorkeling'),
    ItemObject(id: 407, name: 'Snowboarding'),
    ItemObject(id: 408, name: 'Snowmobiling'),
    ItemObject(id: 409, name: 'Snowshoeing'),
    ItemObject(id: 410, name: 'Soccer'),
    ItemObject(id: 411, name: 'Squirrel fishing'),
    ItemObject(id: 412, name: 'Stone skipping'),
    ItemObject(id: 413, name: 'Storm chasing'),
    ItemObject(id: 414, name: 'Sun bathing'),
    ItemObject(id: 415, name: 'Surfing'),
    ItemObject(id: 416, name: 'Survivalism'),
    ItemObject(id: 417, name: 'Swimming'),
    ItemObject(id: 418, name: 'Table tennis playing'),
    ItemObject(id: 419, name: 'Taekwondo'),
    ItemObject(id: 420, name: 'Tai chi'),
    ItemObject(id: 421, name: 'Tennis'),
    ItemObject(id: 422, name: 'Thru-hiking'),
    ItemObject(id: 423, name: 'Topiary'),
    ItemObject(id: 424, name: 'Tourism'),
    ItemObject(id: 425, name: 'Trade fair visiting'),
    ItemObject(id: 426, name: 'Travel'),
    ItemObject(id: 427, name: 'Unicycling'),
    ItemObject(id: 428, name: 'Urban exploration'),
    ItemObject(id: 429, name: 'Vacation'),
    ItemObject(id: 430, name: 'Vegetable farming'),
    ItemObject(id: 431, name: 'Vehicle restoration'),
    ItemObject(id: 432, name: 'Videography'),
    ItemObject(id: 433, name: 'Volleyball'),
    ItemObject(id: 434, name: 'Volunteering'),
    ItemObject(id: 435, name: 'Walking'),
    ItemObject(id: 436, name: 'Water sports'),
    ItemObject(id: 437, name: 'Zoo visiting'),
    ItemObject(id: 438, name: 'Educational hobbies'),
    ItemObject(id: 439, name: 'Archaeology'),
    ItemObject(id: 440, name: 'Architecture'),
    ItemObject(id: 441, name: 'Astronomy'),
    ItemObject(id: 442, name: 'Animation'),
    ItemObject(id: 443, name: 'Aerospace'),
    ItemObject(id: 444, name: 'Biology'),
    ItemObject(id: 445, name: 'Botany'),
    ItemObject(id: 446, name: 'Business'),
    ItemObject(id: 447, name: 'Chemistry'),
    ItemObject(id: 448, name: 'Egyptology'),
    ItemObject(id: 449, name: 'Engineering'),
    ItemObject(id: 450, name: 'Entrepreneurship'),
    ItemObject(id: 451, name: 'Finance'),
    ItemObject(id: 452, name: 'Geography'),
    ItemObject(id: 453, name: 'History'),
    ItemObject(id: 454, name: 'Jurisprudential'),
    ItemObject(id: 455, name: 'Linguistics'),
    ItemObject(id: 456, name: 'Literature'),
    ItemObject(id: 457, name: 'Mathematics'),
    ItemObject(id: 458, name: 'Medical science'),
    ItemObject(id: 459, name: 'Microbiology'),
    ItemObject(id: 460, name: 'Mycology'),
    ItemObject(id: 461, name: 'Myrmecology'),
    ItemObject(id: 462, name: 'Neuroscience'),
    ItemObject(id: 463, name: 'Philosophy'),
    ItemObject(id: 464, name: 'Physics'),
    ItemObject(id: 465, name: 'Psychology'),
    ItemObject(id: 466, name: 'Publishing'),
    ItemObject(id: 467, name: 'Railway studies'),
    ItemObject(id: 468, name: 'Religious studies'),
    ItemObject(id: 469, name: 'Research'),
    ItemObject(id: 470, name: 'Science and technology studies'),
    ItemObject(id: 471, name: 'Social studies'),
    ItemObject(id: 472, name: 'Sociology'),
    ItemObject(id: 473, name: 'Sports science'),
    ItemObject(id: 474, name: 'Story writing'),
    ItemObject(id: 475, name: 'Life science'),
    ItemObject(id: 476, name: 'Teaching'),
    ItemObject(id: 477, name: 'Web design'),
    ItemObject(id: 478, name: 'Wikipedia editing'),
    ItemObject(id: 479, name: 'Collection hobbies'),
    ItemObject(id: 480, name: 'Indoors'),
    ItemObject(id: 481, name: 'Action figure'),
    ItemObject(id: 482, name: 'Antiquing'),
    ItemObject(id: 483, name: 'Ant-keeping'),
    ItemObject(id: 484, name: 'Art collecting'),
    ItemObject(id: 485, name: 'Book collecting'),
    ItemObject(id: 486, name: 'Button collecting'),
    ItemObject(id: 487, name: 'Cartophily (card collecting)'),
    ItemObject(id: 488, name: 'Cassette tapes'),
    ItemObject(id: 489, name: 'Coin collecting'),
    ItemObject(id: 490, name: 'Comic book collecting'),
    ItemObject(id: 491, name: 'Compact discs'),
    ItemObject(id: 492, name: 'Crystals'),
    ItemObject(id: 493, name: 'Deltiology (postcard collecting)'),
    ItemObject(id: 494, name: 'Die-cast toy'),
    ItemObject(id: 495, name: 'Digital hoarding'),
    ItemObject(id: 496, name: 'Dolls'),
    ItemObject(id: 497, name: 'Element collecting'),
    ItemObject(id: 498, name: 'Ephemera collecting'),
    ItemObject(id: 499, name: 'Films'),
    ItemObject(id: 500, name: 'Fingerprint collecting'),
    ItemObject(id: 501, name: 'Fusilately (phonecard collecting)'),
    ItemObject(id: 502, name: 'Knife collecting'),
    ItemObject(id: 503, name: 'Lapel pins'),
    ItemObject(id: 504, name: 'Lotology (lottery ticket collecting)'),
    ItemObject(id: 505, name: 'Movie memorabilia collecting'),
    ItemObject(id: 506, name: 'Notaphily (banknote collecting)'),
    ItemObject(id: 507, name: 'Perfume'),
    ItemObject(id: 508, name: 'Philately'),
    ItemObject(id: 509, name: 'Phillumeny'),
    ItemObject(id: 510, name: 'Radio-controlled model collecting'),
    ItemObject(id: 511, name: 'Rail transport modelling'),
    ItemObject(id: 512, name: 'Record collecting'),
    ItemObject(id: 513, name: 'Rock tumbling'),
    ItemObject(id: 514, name: 'Scutelliphily'),
    ItemObject(id: 515, name: 'Shoes'),
    ItemObject(id: 516, name: 'Slot car'),
    ItemObject(id: 517, name: 'Sneakers'),
    ItemObject(id: 518, name: 'Sports memorabilia'),
    ItemObject(id: 519, name: 'Stamp collecting'),
    ItemObject(id: 520, name: 'Stuffed toy collecting'),
    ItemObject(id: 521, name: 'Tea bag collecting'),
    ItemObject(id: 522, name: 'Ticket collecting'),
    ItemObject(id: 523, name: 'Transit map collecting'),
    ItemObject(id: 524, name: 'Video game collecting'),
    ItemObject(id: 525, name: 'Vintage cars'),
    ItemObject(id: 526, name: 'Vintage clothing'),
    ItemObject(id: 527, name: 'Vinyl records'),
    ItemObject(id: 528, name: 'Outdoors'),
    ItemObject(id: 529, name: 'Antiquities'),
    ItemObject(id: 530, name: 'Auto audiophilia'),
    ItemObject(id: 531, name: 'Flower collecting and pressing'),
    ItemObject(id: 532, name: 'Fossil hunting'),
    ItemObject(id: 533, name: 'Insect collecting'),
    ItemObject(id: 534, name: 'Leaves'),
    ItemObject(id: 535, name: 'Magnet fishing'),
    ItemObject(id: 536, name: 'Metal detecting'),
    ItemObject(id: 537, name: 'Mineral collecting'),
    ItemObject(id: 538, name: 'Rock balancing'),
    ItemObject(id: 539, name: 'Sea glass collecting'),
    ItemObject(id: 540, name: 'Seashell collecting'),
    ItemObject(id: 541, name: 'Stone collecting'),
    ItemObject(id: 542, name: 'Competitive hobbies'),
    ItemObject(id: 543, name: 'Indoors'),
    ItemObject(id: 544, name: 'Air hockey'),
    ItemObject(id: 545, name: 'Animal fancy'),
    ItemObject(id: 546, name: 'Axe throwing'),
    ItemObject(id: 547, name: 'Backgammon'),
    ItemObject(id: 548, name: 'Badminton'),
    ItemObject(id: 549, name: 'Baking'),
    ItemObject(id: 550, name: 'Ballet dancing'),
    ItemObject(id: 551, name: 'Ballroom dancing'),
    ItemObject(id: 552, name: 'Baton twirling'),
    ItemObject(id: 553, name: 'Beauty pageants'),
    ItemObject(id: 554, name: 'Billiards'),
    ItemObject(id: 555, name: 'Book folding'),
    ItemObject(id: 556, name: 'Bowling'),
    ItemObject(id: 557, name: 'Boxing'),
    ItemObject(id: 558, name: 'Bridge'),
    ItemObject(id: 559, name: 'Cooking'),
    ItemObject(id: 560, name: 'Checkers (draughts)'),
    ItemObject(id: 561, name: 'Cheerleading'),
    ItemObject(id: 562, name: 'Chess'),
    ItemObject(id: 563, name: 'Color guard'),
    ItemObject(id: 564, name: 'Cribbage'),
    ItemObject(id: 565, name: 'Curling'),
    ItemObject(id: 566, name: 'Dancing'),
    ItemObject(id: 567, name: 'Darts'),
    ItemObject(id: 568, name: 'Debate'),
    ItemObject(id: 569, name: 'Dominoes'),
    ItemObject(id: 570, name: 'Eating'),
    ItemObject(id: 571, name: 'Esports'),
    ItemObject(id: 572, name: 'Fencing'),
    ItemObject(id: 573, name: 'Figure Skating'),
    ItemObject(id: 574, name: 'Go'),
    ItemObject(id: 575, name: 'Gymnastics'),
    ItemObject(id: 576, name: 'Ice hockey'),
    ItemObject(id: 577, name: 'Ice skating'),
    ItemObject(id: 578, name: 'Judo'),
    ItemObject(id: 579, name: 'Jujitsu'),
    ItemObject(id: 580, name: 'Kabaddi'),
    ItemObject(id: 581, name: 'Knowledge/word games'),
    ItemObject(id: 582, name: 'Laser tag'),
    ItemObject(id: 583, name: 'Magic'),
    ItemObject(id: 584, name: 'Mahjong'),
    ItemObject(id: 585, name: 'Marbles'),
    ItemObject(id: 586, name: 'Martial arts'),
    ItemObject(id: 587, name: 'Model racing'),
    ItemObject(id: 588, name: 'Model United Nations'),
    ItemObject(id: 589, name: 'Pinball'),
    ItemObject(id: 590, name: 'Poker'),
    ItemObject(id: 591, name: 'Pole dancing'),
    ItemObject(id: 592, name: 'Pool'),
    ItemObject(id: 593, name: 'Radio-controlled model playing'),
    ItemObject(id: 594, name: 'Role-playing games'),
    ItemObject(id: 595, name: 'Rughooking'),
    ItemObject(id: 596, name: 'Shogi'),
    ItemObject(id: 597, name: 'Slot car racing'),
    ItemObject(id: 598, name: 'Speedcubing'),
    ItemObject(id: 599, name: 'Speedrunning'),
    ItemObject(id: 600, name: 'Sport stacking'),
    ItemObject(id: 601, name: 'Table football'),
    ItemObject(id: 602, name: 'Table tennis'),
    ItemObject(id: 603, name: 'Tiddlywinks'),
    ItemObject(id: 604, name: 'Volleyball'),
    ItemObject(id: 605, name: 'Video gaming'),
    ItemObject(id: 606, name: 'VR gaming'),
    ItemObject(id: 607, name: 'Weightlifting'),
    ItemObject(id: 608, name: 'Wrestling'),
    ItemObject(id: 609, name: 'Outdoors'),
    ItemObject(id: 610, name: 'Airsoft'),
    ItemObject(id: 611, name: 'Archery'),
    ItemObject(id: 612, name: 'Association football'),
    ItemObject(id: 613, name: 'Australian rules football'),
    ItemObject(id: 614, name: 'Auto racing'),
    ItemObject(id: 615, name: 'Baseball'),
    ItemObject(id: 616, name: 'Beach volleyball'),
    ItemObject(id: 617, name: 'Breakdancing'),
    ItemObject(id: 618, name: 'Capoeira'),
    ItemObject(id: 619, name: 'Climbing'),
    ItemObject(id: 620, name: 'Cornhole'),
    ItemObject(id: 621, name: 'Cricket'),
    ItemObject(id: 622, name: 'Croquet'),
    ItemObject(id: 623, name: 'Cycling'),
    ItemObject(id: 624, name: 'Disc golf'),
    ItemObject(id: 625, name: 'Dog sport'),
    ItemObject(id: 626, name: 'Equestrianism'),
    ItemObject(id: 627, name: 'Exhibition drill'),
    ItemObject(id: 628, name: 'Field hockey'),
    ItemObject(id: 629, name: 'Figure skating'),
    ItemObject(id: 630, name: 'Fishing'),
    ItemObject(id: 631, name: 'Fitness'),
    ItemObject(id: 632, name: 'Footbag'),
    ItemObject(id: 633, name: 'Frisbee'),
    ItemObject(id: 634, name: 'Golfing'),
    ItemObject(id: 635, name: 'Handball'),
    ItemObject(id: 636, name: 'Horseback riding'),
    ItemObject(id: 637, name: 'Horsemanship'),
    ItemObject(id: 638, name: 'Horseshoes'),
    ItemObject(id: 639, name: 'Iceboat racing'),
    ItemObject(id: 640, name: 'Jukskei'),
    ItemObject(id: 641, name: 'Kart racing'),
    ItemObject(id: 642, name: 'Knife throwing'),
    ItemObject(id: 643, name: 'Lacrosse'),
    ItemObject(id: 644, name: 'Longboarding'),
    ItemObject(id: 645, name: 'Long-distance running'),
    ItemObject(id: 646, name: 'Marching band'),
    ItemObject(id: 647, name: 'Mini golf'),
    ItemObject(id: 648, name: 'Model aircraft'),
    ItemObject(id: 649, name: 'Orienteering'),
    ItemObject(id: 650, name: 'Pickleball'),
    ItemObject(id: 651, name: 'Powerboat racing'),
    ItemObject(id: 652, name: 'Quidditch'),
    ItemObject(id: 653, name: 'Race walking'),
    ItemObject(id: 654, name: 'Racquetball'),
    ItemObject(id: 655, name: 'Radio-controlled car racing'),
    ItemObject(id: 656, name: 'Radio-controlled model playing'),
    ItemObject(id: 657, name: 'Roller derby'),
    ItemObject(id: 658, name: 'Rugby league football'),
    ItemObject(id: 659, name: 'Sculling or rowing'),
    ItemObject(id: 660, name: 'Shooting sports'),
    ItemObject(id: 661, name: 'Skateboarding'),
    ItemObject(id: 662, name: 'Skiing'),
    ItemObject(id: 663, name: 'Sled dog racing'),
    ItemObject(id: 664, name: 'Softball'),
    ItemObject(id: 665, name: 'Speed skating'),
    ItemObject(id: 666, name: 'Squash'),
    ItemObject(id: 667, name: 'Surfing'),
    ItemObject(id: 668, name: 'Swimming'),
    ItemObject(id: 669, name: 'Table tennis'),
    ItemObject(id: 670, name: 'Tennis'),
    ItemObject(id: 671, name: 'Tennis polo'),
    ItemObject(id: 672, name: 'Tether car'),
    ItemObject(id: 673, name: 'Tour skating'),
    ItemObject(id: 674, name: 'Tourism'),
    ItemObject(id: 675, name: 'Trapshooting'),
    ItemObject(id: 676, name: 'Triathlon'),
    ItemObject(id: 677, name: 'Ultimate frisbee'),
    ItemObject(id: 678, name: 'Volleyball'),
    ItemObject(id: 679, name: 'Water polo'),
    ItemObject(id: 680, name: 'Observation hobbies'),
    ItemObject(id: 681, name: 'Indoors'),
    ItemObject(id: 682, name: 'Audiophile'),
    ItemObject(id: 683, name: 'Cuckolding'),
    ItemObject(id: 684, name: 'Ant farming'),
    ItemObject(id: 685, name: 'Fishkeeping'),
    ItemObject(id: 686, name: 'Learning'),
    ItemObject(id: 687, name: 'Meditation'),
    ItemObject(id: 688, name: 'Microscopy'),
    ItemObject(id: 689, name: 'Reading'),
    ItemObject(id: 690, name: 'Research'),
    ItemObject(id: 691, name: 'Shortwave listening'),
    ItemObject(id: 692, name: 'Outdoors'),
    ItemObject(id: 693, name: 'Aircraft spotting'),
    ItemObject(id: 694, name: 'Amateur astronomy'),
    ItemObject(id: 695, name: 'Beekeeping'),
    ItemObject(id: 696, name: 'Benchmarking'),
    ItemObject(id: 697, name: 'Birdwatching'),
    ItemObject(id: 698, name: 'Bus spotting'),
    ItemObject(id: 699, name: 'Butterfly watching'),
    ItemObject(id: 700, name: 'Geocaching'),
    ItemObject(id: 701, name: 'Gongoozling'),
    ItemObject(id: 702, name: 'Herping'),
    ItemObject(id: 703, name: 'Hiking/backpacking'),
    ItemObject(id: 704, name: 'Meteorology'),
    ItemObject(id: 705, name: 'People-watching'),
    ItemObject(id: 706, name: 'Photography'),
    ItemObject(id: 707, name: 'Satellite watching'),
    ItemObject(id: 708, name: 'Trainspotting'),
    ItemObject(id: 709, name: 'Whale watching'),
  ];

  static final Preferences _instance = Preferences._internal();

  factory Preferences() {
    return _instance;
  }

  Preferences._internal();

  List<ItemObject> getPreferences() {
    return preferencesList;
  }
}
