// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVAOdwIKBq9nMurdPswSctUn3opQa3NeU',
    appId: '1:533745140020:web:691e95d5dbb84550b9e561',
    messagingSenderId: '533745140020',
    projectId: 'social-hive-places',
    authDomain: 'social-hive-places.firebaseapp.com',
    storageBucket: 'social-hive-places.appspot.com',
    measurementId: 'G-CSRWGQGXJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvYOygHInFvjHH6c2clLQR_67KJgwbSs',
    appId: '1:533745140020:android:7dd9fe676ec30cfdb9e561',
    messagingSenderId: '533745140020',
    projectId: 'social-hive-places',
    storageBucket: 'social-hive-places.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu2Qup9LiiBAp-DUlReOVo2zKcCvi1908',
    appId: '1:533745140020:ios:5010413cd8f0502cb9e561',
    messagingSenderId: '533745140020',
    projectId: 'social-hive-places',
    storageBucket: 'social-hive-places.appspot.com',
    iosClientId: '533745140020-vapkpaa20mpt0nmr1f0u9j6b0dbgle1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialHiveClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu2Qup9LiiBAp-DUlReOVo2zKcCvi1908',
    appId: '1:533745140020:ios:5010413cd8f0502cb9e561',
    messagingSenderId: '533745140020',
    projectId: 'social-hive-places',
    storageBucket: 'social-hive-places.appspot.com',
    iosClientId: '533745140020-vapkpaa20mpt0nmr1f0u9j6b0dbgle1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialHiveClient',
  );
}
